# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qq-S5Twcb6nb7fB8KA6y5qs4phSihaS6
"""

'''Syed Muhammad Razi
Task 1'''
names = ["Hasnain" , "Sohaib" , "Rizwan" , "Moazzam" , "Adnan"]
print(names[0])
print(names[1])
print(names[2])
print(names[3])
print(names[4])

'''Syed Muhammad Razi
Task 2'''
print(names[0] , "is my friend")
print(names[1] , "is my friend")
print(names[2] , "is my friend")
print(names[3] , "is my friend")
print(names[4] , "is my friend")

'''Syed Muhammad Razi
Task 3'''
vehicle = ["Bike" , "Foot" , "Cycle" , "Aeroplane" , "Rocket"]
print ("I would like to travel on" , vehicle[0])
print ("I would like to travel on" , vehicle[1])
print ("I would like to travel on" , vehicle[2])
print ("I would like to travel on" , vehicle[3])
print ("I would like to travel on" , vehicle[4])

'''Syed Muhammad Razi
Task 4'''
invitees = ["Hasnain" , "Sohaib" , "Rizwan"]
print(invitees[0] , "please come to my home for iftaar")
print(invitees[1] , "please come to my home for iftaar")
print(invitees[2] , "please come to my home for iftaar")

'''Syed Muhammad Razi
Task 5'''
print(invitees[0] , "would not be able to come today")
invitees[0] = "Razi"
print(invitees[0] , "please come to my home for iftaar")
print(invitees[1] , "please come to my home for iftaar")
print(invitees[2] , "please come to my home for iftaar")

'''Syed Muhammad Razi
Task 6'''
print("We just found a bigger table guests :)")
invitees.insert(0 , "Moazzam")
invitees.insert(3 , "Adnan")
invitees.append("Rizwan")
print(invitees[0] , "please come to my home for iftaar")
print(invitees[1] , "please come to my home for iftaar")
print(invitees[2] , "please come to my home for iftaar")
print(invitees[3] , "please come to my home for iftaar")
print(invitees[4] , "please come to my home for iftaar")
print(invitees[5] , "please come to my home for iftaar")

'''Syed Muhammad Razi
Task 7'''
print("Sorry guys the table wont be arriving in time")
for x in range(len(invitees) , 2 , -1):
  x = x - 1
  print("Sorry" , invitees[x] , "you are not invited now")
  invitees.pop()
print(invitees[0] , "you are still invited")
print(invitees[1] , "you are still invited")
del invitees[1]
del invitees[0]
invitees

'''Syed Muhammad Razi
Task 8'''
places = ["Thar" , "Ghotki" , "Khuzdar" , "Balakot" , "Swat"]
print(places)
print(sorted(places))
print(places)
print(sorted(places , reverse = True))
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print (places)
places.sort(reverse = True)
print (places)

'''Syed Muhammad Razi
Task 9'''
invited = ["Sohaib" , "Rizwan" , "Hasnain"]
print(len(invited))

'''Syed Muhammad Razi
Task 10'''
country = ["Afghanistan" , "Iran" , "China" , "Pakistan" , "India" , "Srilanka" , "Bangladesh" , "India" , "Honkong" , "Nepal"]
country[7] = "Japan"
print (country)
country.insert(0 , "Malysia")
print(country[-1::-1])
country.reverse()
print(country)
del country [2]
print(country)
country.remove("Srilanka")
print (country)
for i in range(len(country)):
  print(country[i].upper())
for i in range(len(country)):
  print(country[i].lower())
print(sorted(country))
print(country)
print(sorted(country , reverse = True))

'''Syed Muhammad Razi
Task 11'''
cars = ["Toyota" , "Changhan" , "Honda" , "Suzuki"]
print(cars[2])

'''Syed Muhammad Razi
Task 11
Chapter 4 : 4.1'''
pizza = ["jalapeno" , "barbeque" , "fajita"]
for i in range(len(pizza)):
  print("I like" , pizza[i] , "pizza")
print("I can eat pizza daily")

'''Syed Muhammad Razi
Task 11
Chapter 4 : 4.2'''
animals = ["whale" , "shark" , "turtle"]
for i in range(len(animals)):
  print(animals[i])
print(animals[0] , "is the biggest sea creature")
print(animals[1] , "is the wildest sea creature")
print(animals[2] , "is the slowest sea creature")
print("All these animals can survive in water")

'''Syed Muhammad Razi
Task 11
Chapter 4 : 4.3'''
for i in range(1 , 21):
  print(i , end = "  ")

'''Syed Muhammad Razi
Task 11
Chapter 4 : 4.4'''
for i in range(1 , 1000000):
  print(i , end = " ")

'''Syed Muhammad Razi
Task 11
Chapter 4 : 4.5'''
sum = 0
for i in range(1 , 1000000):
  sum = sum + i
print(sum)

'''Syed Muhammad Razi
Task 11
Chapter 4 : 4.6'''
for i in range(1 , 20 , 2):
  print(i , end = "  ")

'''Syed Muhammad Razi
Task 11
Chapter 4 : 4.7'''
for i in range(1 , 11):
  print(3*i , end = "  ")

'''Syed Muhammad Razi
Task 11
Chapter 4 : 4.8'''
for i in range(1 , 11):
  print(i**3 , end = "  ")

'''Syed Muhammad Razi
Task 11
Chapter 4 : 4.9'''
cube = [i**3 for i in range(1 , 11)]
cube

'''Syed Muhammad Razi
Task 11
Chapter 4 : 4.10'''
country = ["Afghanistan" , "Iran" , "China" , "Pakistan" , "India" , "Srilanka" , "Bangladesh" , "Malysia" , "Honkong" , "Nepal"]
print("The first 3 countries are:")
print(country[:3])
print ("The middle 3 countries are:")
print (country[3:6])
print ("The last 3 countries are:")
print(country[-3:])

'''Syed Muhammad Razi
Task 11
Chapter 4 : 4.11'''
my_pizza = ["jalapeno" , "barbeque" , "fajita"]
friend_pizza = my_pizza[:]
my_pizza.append("pepperoni")
friend_pizza.append("staek")
print("My pizzas are:" , my_pizza)
print("My fieind pizzas are:" , friend_pizza)

'''Syed Muhammad Razi
Task 11
Chapter 4 : 4.12'''
for i in range(4):
  print(my_pizza[i] , end = " ")
print()
for i in range(4):
  print(friend_pizza[i] , end = " ")

'''Syed Muhammad Razi
Task 11
Chapter 4 : 4.13'''
menu = ("Karahi" , "Biryani" , "Barbeque" , "Sushi" , "Burgers")
print("Original menu:")
for menu in menu:
  print(menu)
menu = ("Karahi" , "Biryani" , "Rolls" , "Sushi" , "Pizza")
print("\nModified menu:")
for menu in menu:
  print(menu)

'''Syed Muhammad Razi
Task 12
Chapter 5 : 5.1'''
car = 'subaru'
print("Is car == 'subaru'? I predict True.")
print(car == 'subaru')
print("\nIs car == 'audi'? I predict False.")
print(car == 'audi')
bike = 'CD70'
print("Is bike == 'CD70'? I predict True.")
print(bike == 'CD70')
print("\nIs car == 'Honda 125'? I predict False.")
print(car == 'Honda 125')
plane = 'AirBlue'
print("Is plane == 'PIA'? I predict True.")
print(plane == 'PIA')
print("\nIs plane = 'AirBlue'? I predict False.")
print(plane == 'AirBlue')
truck = "Nissan"
print("Is truck == 'Maruti'? I predict True.")
print(truck == 'Maruti')
print("\nIs car == 'Nissan'? I predict False.")
print(truck == 'Nissan')

'''Syed Muhammad Razi
Task 12
Chapter 5 : 5.2'''
string = "My name is Razi"
inp = input("Enter string: ")
if inp == string:
  print("Welcome Razi")
else:
  print("Permission rejected")

string = "my name is razi"
if string.islower == True:
  print("String is in lower case")
else:
  print("String is not in lower case")

a = int(input("Enter any integer: "))
if a < 100 and a > 0:
  print("Entered integer is between 0 and 100")
else:
  print("Entered integer is not between 0 and 100")

places = ["Thar" , "Ghotki" , "Khuzdar" , "Balakot" , "Swat"]
if 'Thar' in places:
  print ("Item found in the list")
else:
  print ("Item not found in the list")

places = ["Thar" , "Ghotki" , "Khuzdar" , "Balakot" , "Swat"]
if 'Karachi' in places:
  print ("Item found in the list")
else:
  print ("Item not found in the list")

'''Syed Muhammad Razi
Task 12
Chapter 5 : 5.3'''
alien_color = 'green'
if alien_color == 'green':
  print('You just earned 5 points')

alien_color = 'red'
if alien_color == 'green':
  print('You just earned 5 points')
else:
  print('You hit the wrong alien')

'''Syed Muhammad Razi
Task 12
Chapter 5 : 5.4'''
alien_color = 'green'
if alien_color == 'green':
  print('You just earned 5 points')

alien_color = 'red'
if alien_color == 'green':
  print('You just earned 5 points')
else:
  print('You just earned 10 points')

'''Syed Muhammad Razi
Task 12
Chapter 5 : 5.5'''
alien_color = input("Enter the color of alien: ")
if alien_color == 'green':
  print('You just earned 5 points')
elif alien_color == 'yellow':
  print('You just earned 10 points')
else:
  print('You just earned 15 points')

'''Syed Muhammad Razi
Task 12
Chapter 5 : 5.6'''
age = int(input("Enter your age: "))
if age < 2:
  print("The person is a baby")
elif age > 2 and age < 4:
  print("The person is a toddler")
elif age > 4 and age < 13:
  print("The person is a kid")
elif age > 13 and age < 20:
  print("The person is a teenager")
elif age > 20 and age < 65:
  print("The person is an adult")
else:
  print("The person is an elder")

'''Syed Muhammad Razi
Task 12
Chapter 5 : 5.7'''
fruits = ['apple' , 'banana' , 'srtawberry' , 'peach' , 'kiwi' , 'watermelon']
ans = input("Enter any fruit: ")
for fruit in fruits:
  if fruit == ans:
    print ("I realy like" , fruit)
ans = input("Enter any fruit: ")
for fruit in fruits:
  if fruit == ans:
    print ("I realy like" , fruit)
ans = input("Enter any fruit: ")
for fruit in fruits:
  if fruit == ans:
    print ("I realy like" , fruit)
ans = input("Enter any fruit: ")
for fruit in fruits:
  if fruit == ans:
    print ("I realy like" , fruit)

'''Syed Muhammad Razi
Task 12
Chapter 5 : 5.8'''
users = ['Razi' , 'Hasnain' , 'Sohaib' , 'Admin' , 'User']
for user in users:
  if user == 'Admin':
    print("Hello" , user , "would you like to see a status report?")
  else:
    print("Hello" , user , "thank you for logging in again")

'''Syed Muhammad Razi
Task 12
Chapter 5 : 5.9'''
users = ['Razi' , 'Hasnain' , 'Sohaib' , 'Admin' , 'User']
for i in range(len(users)):
  users.pop()
if users: 
  print("Dont run")
else:
  print("We need to find some users")

'''Syed Muhammad Razi
Task 12
Chapter 5 : 5.10'''
current_users = ['Razi' , 'Hasnain' , 'Sohaib' , 'Admin' , 'User']
new_users = ['azhar' , 'zaky' , 'admin' , 'user']
new_users = [name.capitalize() for name in new_users]
for new in new_users:
  for old in current_users:
    positive = 0
    negative = 0
    if new  != old:
      positive += 1
      #print(new , "can be used as a username")
    else:
      negative += 1
      #print("Username already taken")
  if positive >= 2:
    print(new , "can be used as a username")
  if negative >= 2:
    print("Username already taken")

number = [1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9]
for i in number:
  print ("This is number" , i)

"""Task related to string and input method"""

'''Syed Muhammad Razi
Task 1'''
var = input("Enter a name: ")
print ("Hello " + var + "!")

'''Syed Muhammad Razi
Task 2'''
var1 = input("Enter first string: ")
var2 = input("Enter first string: ")
print(var1+var2+var2+var1)

'''Syed Muhammad Razi
Task 3'''
var = input("Ennter a string: ")
print(var[-2:]*3)

'''Syed Muhammad Razi
Task 4'''
string = input("Enter a string: ")
var = string.replace(" " , "")
print(var)

'''Syed Muhammad Razi
Task 5'''
var = input("Enter a string: ")
print(var[:2])

'''Syed Muhammad Razi
Task 6'''
var = input("Enter a string: ")
half = len(var)/2
half = int(half)
print(var[:half])

'''Syed Muhammad Razi
Task 7'''
var = input("Enter a string: ")
if len(var) > 2:
  print(var[1:-1])

'''Syed Muhammad Razi
Task 8'''
var1 = input("Enter first string: ")
var2 = input("Enter second string: ")
if len(var1) > 2 and len(var2) > 2:
  print(var1[1:] + var2[1:])

"""Task related to numbers and input method"""

'''Syed Muhammad Razi
Task 1'''
import math as mt
a = int(input("Enter any number: "))
b = int(input("Enter any number: "))
c = int(input("Enter any number: "))
x1 = (-b + mt.sqrt(b*b - 4*a*c)/2*a)
x2 = (-b - mt.sqrt(b*b - 4*a*c)/2*a)

print ("The roots are: " , x1 , "and" , x2)

import math as mt
x = int(input("Enter any number: "))
xy = x+1/x
xyz = x-1/x
ans = mt.sqrt(xy**2 - 4*xyz)
print ("Answer: " , ans)

